### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte...

### ISSUE THREAD

**Issue by jbaf** [blitzrk/sublime_libsass#12]
Hello !

New error (sorry) :
I was trying to use your plugin on a new project, and I have a new issue with building from partials, but this time it doesn't matter if the partial is in a subfolder, and if the @import declaration is not indented either. And this time, I have an error in the console (but none shown in the status bar...).

Here's the error it shows : 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 551, in run_
    return self.run(**args)
  File "compile in /Users/graphiste6tk/Library/Application Support/Sublime Text 3/Installed Packages/Libsass Build.sublime-package", line 42, in run
  File "compile in /Users/graphiste6tk/Library/Application Support/Sublime Text 3/Installed Packages/Libsass Build.sublime-package", line 18, in compile_deps
  File "libsass.deps in /Users/graphiste6tk/Library/Application Support/Sublime Text 3/Installed Packages/Libsass Build.sublime-package", line 56, in get
  File "libsass.deps in /Users/graphiste6tk/Library/Application Support/Sublime Text 3/Installed Packages/Libsass Build.sublime-package", line 45, in get_rec
  File "libsass.pathutils in /Users/graphiste6tk/Library/Application Support/Sublime Text 3/Installed Packages/Libsass Build.sublime-package", line 54, in grep_r
  File "libsass.pathutils in /Users/graphiste6tk/Library/Application Support/Sublime Text 3/Installed Packages/Libsass Build.sublime-package", line 43, in in_file
  File "./encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 299: ordinal not in range(128)
```

And here is the content of my conf file : 

```
{
    "output": {
        "dir": "maquette/css",      // Relative or absolute path (can have ..)
        "structure": ["nested", "maquette/scss"]      // "flat", "nested", or ["nested", "relative/root/of/nest"]
    },
    "compile": {
        "style": "compressed",      // String | Output style: nested/expanded/compact/compressed
        "line-numbers": false,      // Bool   | Emit comments showing original line numbers
        "line-comments": false,     // Bool   | Alias for line-numbers, does not override
        "load-path": false,         // List   | Sass import paths: e.g. [ "C:\bourbon", "C:\compass" ]
        "plugin-path": false,       // String | Path to autoload plugins (libsass issue 878)
        "sourcemap": true,          // Bool   | Emit .css.map file for debugging in browser
        "omit-map-comment": false,  // Bool   | Omit comment about .css.map file in .css file
        "precision": false          // Int    | Decimal places for computed values
    }
}
```

And again, it happens only when compiling from partials. Compiling from my `main.scss` file seems to work.
Any Ideas ?

**Comment by blitzrk** [comment]
Thanks for finding another bug.

I do know what's going on. There's a file (with a .sass or .scss extension) that it's trying to read (to see which partials it imports) that has a character Python can't read. So I'm guessing you have a special character somewhere that Python is having trouble with, but the error message is horrible.

I will add some debugging ASAP to point out for which file and which line this is occurring. Then I will also try to skip files that can't be read and emit warnings that they're being skipped.

**Comment by blitzrk** [comment]
Couldn't ever reproduce your problem, but I still attempted a solution and added some debug info. So let me know what you get now on 0.9.4. It'll hopefully at least point out the file and line it's failing on.

**Comment by jbaf** [comment]
Well I don't know what you did exactly, but it works perfectly now.
No error at all.  Great job !
The only down side is that we will never know what caused the bug...
Thanks a lot, anyway !

**Comment by blitzrk** [comment]
Oh, haha. Awesome! All I did was assert what should have been the default, anyway.

You're welcome. :)
