### ISSUE TITLE
Imports broken on ST2

### ISSUE THREAD

**Issue by blitzrk** [blitzrk/sublime_libsass#13]
Not sure what changed that broke them. Need to do a bisection.

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./compile.py", line 12, in <module>
    from .libsass import deps
ValueError: Attempted relative import in non-package
Reloading plugin /home/ben/.config/sublime-text-2/Packages/sublime_libsass/config.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./config.py", line 10, in <module>
    from .libsass import project
ValueError: Attempted relative import in non-package
```

**Comment by blitzrk** [comment]
Pushed commit for testing.

**Comment by blitzrk** [comment]
Finally got it working on all platforms. Need to write tests for this, but that will be another issue.
