### ISSUE TITLE
sublime_libsass not compiling since update 0.9.10

### ISSUE THREAD

**Issue by jbaf** [blitzrk/sublime_libsass#19]
Hello again.

The question is in the title of the issue. Since I updated to 0.9.10, my scss won't be builded, and neither will it for my colleague on windows.
Here is the error I get : 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 551, in run_
    return self.run(**args)
  File "compile in /Users/graphiste6tk/Library/Application Support/Sublime Text 3/Installed Packages/Libsass Build.sublime-package", line 64, in run
  File "compile in /Users/graphiste6tk/Library/Application Support/Sublime Text 3/Installed Packages/Libsass Build.sublime-package", line 108, in __init__
NameError: global name 'file_path' is not defined
```

Thank you in advance for your answer ;)

**Comment by blitzrk** [comment]
Duplicate #18
